// packages/cli/templates/WatchThroughAccessory/svelte/WatchThroughAccessory.svelte
<script lang="ts">
  import {getApi} from '@watching/clips-svelte';
  import type {WatchThroughQueryData} from './WatchThroughQuery.graphql';

  const {target, query} = getApi<
    'watch-through.details.accessory',
    WatchThroughQueryData
  >();
</script>

<ui-block-stack spacing={true}>
  <ui-text-block>
    You are rendering in the <ui-text emphasis={true}>{target}</ui-text>
    extension point, on a series named
    <ui-text emphasis={true}>{$query.watchThrough.series.name}</ui-text>!
  </ui-text-block>

  {#if $query.watchThrough.currentWatch != null}
    {#if $query.watchThrough.currentWatch.rating == null}
      <ui-text-block>You haven’t rated this episode yet.</ui-text-block>
    {:else}
      <ui-text-block>
        You’ve rated this episode <ui-text emphasis={true}
          >{$query.watchThrough.currentWatch.rating}</ui-text
        >.
      </ui-text-block>
    {/if}
  {/if}
</ui-block-stack>

// packages/cli/templates/WatchThroughAccessory/preact/WatchThroughAccessory.tsx
import {
  extension,
  useQuery,
  useApi,
  Text,
  TextBlock,
  BlockStack,
} from '@watching/clips-preact';
import {type WatchThroughQueryData} from './WatchThroughQuery.graphql';

export function Extension() {
  const {target} = useApi();
  const {watchThrough} = useQuery<WatchThroughQueryData>();
  const {series, currentWatch} = watchThrough;

  let currentWatchContent = null;

  if (currentWatch) {
    currentWatchContent =
      currentWatch.rating == null ? (
        <TextBlock>You haven’t rated this episode yet.</TextBlock>
      ) : (
        <TextBlock>
          You’ve rated this episode <Text emphasis>{currentWatch.rating}</Text>.
        </TextBlock>
      );
  }

  return (
    <BlockStack spacing>
      <TextBlock>
        You are rendering in the <Text emphasis>{target}</Text> extension point,
        on a series named <Text emphasis>{series.name}</Text>!
      </TextBlock>

      {currentWatchContent}
    </BlockStack>
  );
}

export default extension<
  'watch-through.details.accessory',
  WatchThroughQueryData
>(() => <Extension />);
