// packages/cli/templates/SeriesAccessory/preact/SeriesAccessory.tsx
import {
  extension,
  useQuery,
  useApi,
  Text,
  TextBlock,
} from '@watching/clips-preact';
import {type SeriesQueryData} from './SeriesQuery.graphql';

export function Extension() {
  const {target} = useApi();
  const {series} = useQuery<SeriesQueryData>();

  return (
    <TextBlock>
      You are rendering in the <Text emphasis>{target}</Text> extension point,
      on a series named <Text emphasis>{series.name}</Text>!
    </TextBlock>
  );
}

export default extension<'series.details.accessory', SeriesQueryData>(() => (
  <Extension />
));

// packages/cli/templates/SeriesAccessory/svelte/SeriesAccessory.svelte
<script lang="ts">
  import {getApi} from '@watching/clips-svelte';
  import type {SeriesQueryData} from './SeriesQuery.graphql';

  const {target, query} = getApi<'series.details.accessory', SeriesQueryData>();
</script>

<ui-text-block>
  You are rendering in the <ui-text emphasis={true}>{target}</ui-text>
  extension point, on a series named
  <ui-text emphasis={true}>{$query.series.name}</ui-text>!
</ui-text-block>
